CLUSTAL multiple sequence alignment by MUSCLE (3.8)


Mus_musculus               MEWVWALVLLAALGGGSAERDCRVSSFRVKENFDKARFSGLWYAIAKKDPEGLFLQDNII
Oryctolagus_cuniculus      MEWVWALVLLAALGSGRGERDCRVSSFRVKENFDKARFAGTWYAMAKKDPEGLFLQDNIV
Homo_sapiens               MKWVWALLLLAALGSGRAERDCRVSSFRVKENFDKARFSGTWYAMAKKDPEGLFLQDNIV
Equus_caballus             MEWVWALVVLAALGSAGAERDCRVSSFRVKENFDKARFSGTWYAMAKKDPEGLFLQDNIV
Felis_catus                MAWVWALVLLAALGSARAERDCRVSSFRVKENFDKARFSGTWYAMAKKDPEGLFLQDNIV
Toxoplasma_gondii          MEWVWALVLLAALGSAQAERDCRVSSFRVKENFDKARFSGTWYAMAKKDPEGLFLQDNIV
Sus_scrofa                 MEWVWALVLLAALGSAQAERDCRVSSFRVKENFDKARFSGTWYAMAKKDPEGLFLQDNIV
Bos_taurus                 MEWVWALVLLAALGSARAERDCRVSSFRVKENFDKARFAGTWYAMAKKDPEGLFLQDNIV
Capra_hircus               MEWVCALVLLAALGSARAERDCRVSSFRVKENFDKARFAGTWYAMAKKDPEGLFLQDNIV
                           * ** **::*****.. .********************:* ***:**************:

Mus_musculus               AEFSVDEKGHMSATAKGRVRLLSNWEVCADMVGTFTDTEDPAKFKMKYWGVASFLQRGND
Oryctolagus_cuniculus      AEFSVDENGHMSATAKGRVRLLNNWDVCADMVGTFTDTEDPAKFKMKYWGVASFLQRGND
Homo_sapiens               AEFSVDETGQMSATAKGRVRLLNNWDVCADMVGTFTDTEDPAKFKMKYWGVASFLQKGND
Equus_caballus             AEFSVDEYGQMSATAKGRVRLLNNWDVCADMVGTFTDTEDPAKFKMKYWGVASFLQKGND
Felis_catus                AEFSVDENGQMSATAKGRVRLLNNWDVCADMVGTFTDTEDSAKFKMKYWGVASFLQKGND
Toxoplasma_gondii          AEFSVDENGHMSATAKGRVRLLNNWDVCADMVGTFTDTEDPAKFKMKYWGVASFLQKGND
Sus_scrofa                 AEFSVDENGHMSATAKGRVRLLNNWDVCADMVGTFTDTEDPAKFKMKYWGVASFLQKGND
Bos_taurus                 AEFSVDENGHMSATAKGRVRLLNNWDVCADMVGTFTDTEDPAKFKMKYWGVASFLQKGND
Capra_hircus               AEFSVDENGHMSATAKGRVRLLNNWDVCADMVGTFTDTEDPAKFKMKYWGVASFLQKGND
                           ******* *:************.**:**************.***************.***

Mus_musculus               DHWIIDTDYDTFALQYSCRLQNLDGTCADSYSFVFSRDPNGLSPETRRLVRQRQEELCLE
Oryctolagus_cuniculus      DHWIIDTDYDTFAVQYSCRLLNFDGTCADSYSFVFSRDPHGLPPDVQKLVRQRQEELCLS
Homo_sapiens               DHWIVDTDYDTYAVQYSCRLLNLDGTCADSYSFVFSRDPNGLPPEAQKIVRQRQEELCLA
Equus_caballus             DHWIIDTDYDTYAVQYSCRLLNLDGTCADSYSFVFARDPNGFPPEVQRIVRRRQEELCLA
Felis_catus                DHWIIDTDYDTYAVQYSCRLLNLDGTCADSYSFVFARDPNGLPPDVQKIVRQRQDELCLA
Toxoplasma_gondii          DHWIIDTDYDTYAVQYSCRLQNLDGTCADSYSFVFARDPHGFSPEVQKIVRQRQEELCLA
Sus_scrofa                 DHWIIDTDYDTYAVQYSCRLQNLDGTCADSYSFVFARDPHGFSPEVQKIVRQRQEELCLA
Bos_taurus                 DHWIIDTDYETFAVQYSCRLLNLDGTCADSYSFVFARDPSGFSPEVQKIVRQRQEELCLA
Capra_hircus               DHWIIDTDYETYAVQYSCRLLNLDGTCADSYSFVFARDPSGFAPEVQKIVRQRQEELCLA
                           ****:****:*:*:****** *:************:*** *:.*:...:**.**:**** 

Mus_musculus               RQYRWIEHNGYCQSRPSRNSL
Oryctolagus_cuniculus      RQYRLIVHNGYCDDKSVRNLL
Homo_sapiens               RQYRLIVHNGYCDGRSERNLL
Equus_caballus             RQYRLISHNGYCDGKSDRNLL
Felis_catus                RQYRLIVHNGYCDGKSEQNIL
Toxoplasma_gondii          RQYRLITHNGYCDGKSERNIL
Sus_scrofa                 RQYRLITHNGYCDGKSERNIL
Bos_taurus                 RQYRLIPHNGYCDGKSERNIL
Capra_hircus               RQYRLIPHNGYCDGKSERNIL
                           **** * *****:... .* *
